stages:
  - test
  - lint
  - deploy

variables:
  DOCKER_IMAGE_NAME: "olooeez/$CI_PROJECT_NAME"
  DOCKER_IMAGE_TAG: "$CI_COMMIT_TAG"

build:
  stage: test
  script:
    - bundle install
    - bundle exec rspec
  tags:
    - ruby

test:
  stage: lint
  script:
    - bundle install
    - bundle exec rubocop
  tags:
    - ruby

deploy:
  stage: deploy
  only:
    - tags
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" .
    - docker push "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
    - docker tag "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" "$DOCKER_IMAGE_NAME:latest"
    - docker push "$DOCKER_IMAGE_NAME:latest"
  tags:
    - docker
